### ISSUE TITLE
Update UI for the Profile Screen

### ISSUE THREAD

**Issue by PrarabdhGarg** [PrarabdhGarg/Radar#10]
The link for the updated UI can be found at:
https://xd.adobe.com/view/3884d012-2dd1-4f15-bfa3-e80f6e45e473-6dd7/specs/
You might want to modify the file `lib/profile/ProfileScreen.dart`

**Comment by error404-beep** [comment]
Hey @PrarabdhGarg , I would like to work on this issue.

**Comment by PrarabdhGarg** [comment]
Great. Go ahead
