### ISSUE TITLE
Handle Overflow while creating requests

### ISSUE THREAD

**Issue by PrarabdhGarg** [PrarabdhGarg/Radar#11]
Currently, if the width of the device is small, the text fields in the create request dialog box overflow, which should not happen.
The width of the text fields should be made dynamic, so that it adjusts according to the width of the screen.
Here is a screenshot for reference.
![WhatsApp Image 2020-07-26 at 10 49 25](https://user-images.githubusercontent.com/42096726/88472218-2423e980-cf2e-11ea-8a08-16ac4a9014fe.jpeg)

**Comment by Garg-Akshat** [comment]
I would like to solve this

**Comment by PrarabdhGarg** [comment]
Sure. Go Ahead.

**Comment by Garg-Akshat** [comment]
## I have made a few changes in the UI of the dialog box and resolved all the overflows, please check the following screenshots of both larger and smaller screen.
### **Small Screen Device**
![Screenshot_2020-08-03-02-05-53-429_com example Radar](https://user-images.githubusercontent.com/60299232/89132261-98631c00-d530-11ea-9a51-0b088a299738.jpg)
![Screenshot_2020-08-03-02-19-34-998_com example Radar](https://user-images.githubusercontent.com/60299232/89132264-99944900-d530-11ea-9684-e851a41fe5de.jpg)
### **Large Screen Device**
![Screenshot_20200803-021925](https://user-images.githubusercontent.com/60299232/89132265-9a2cdf80-d530-11ea-9971-0ba2d78f9a91.jpg)
![Screenshot_20200803-021949](https://user-images.githubusercontent.com/60299232/89132267-9ac57600-d530-11ea-959d-d32ed4660b82.jpg)

**Comment by PrarabdhGarg** [comment]
@akshatgarg18 could you add these images in the PR instead. It would be better for anyone in the future referencing the PR.

**Comment by Garg-Akshat** [comment]
Sure, didn't knew about this, will do it

**Comment by Garg-Akshat** [comment]
@PrarabdhGarg i have edited the PR, please check it
