### ISSUE TITLE
Remove restriction on Google Sign-in

### ISSUE THREAD

**Issue by PrarabdhGarg** [PrarabdhGarg/Radar#13]
Currently, one can only sign-in on the app using a valid BITS e-mail id. This restriction needs to be removed.
You might need to modify `lib/aut/AuthRepository.dart`

**Comment by pavankalyan0424** [comment]
I would like to work on this issue.

**Comment by PrarabdhGarg** [comment]
Sure.

**Comment by Penguin-12** [comment]
This issue was resolved in PR #14 .
