### ISSUE TITLE
Empty messages in chats should not be allowed

### ISSUE THREAD

**Issue by PrarabdhGarg** [PrarabdhGarg/Radar#21]
Currently, there is no sanity check on the messages that can be sent once two devices are connected. At least we should not allow empty messages to be sent, as it is just a waste of resources

**Comment by kohinoor98** [comment]
Hi you can assign this to me
and give permission to - kohinoorchatterjee1998@gmail.com to sign in via google sign in

**Comment by maplerichie** [comment]
Ready to submit pull request

**Comment by maplerichie** [comment]
Pull request sent. Forget to inform for assignment before this. Thanks
