### ISSUE TITLE
Handle overflow while chatting with user 

### ISSUE THREAD

**Issue by Garg-Akshat** [PrarabdhGarg/Radar#22]
### Here is a screenshot for reference.
![WhatsApp Image 2020-08-03 at 2 18 33 AM](https://user-images.githubusercontent.com/60299232/89208998-154ad000-d5db-11ea-97c8-9ff7fddf138d.jpeg)

**Comment by maplerichie** [comment]
Pull request sent. Forget to inform for assignment before this. Thanks
