### ISSUE TITLE
Implement logout feature.

### ISSUE THREAD

**Issue by Penguin-12** [PrarabdhGarg/Radar#25]
Currently there is a logout icon button in the profile page appbar. Add logout functionality to this button.

**Comment by pavankalyan0424** [comment]
I would like to work on this issue.
Doubt: 1.)after logout, should the user be navigated to the login page??
2.)After logout, the key-value pairs (Secure Storage)should be deleted or keys should be assigned as null.

**Comment by Penguin-12** [comment]
Sure, you can work on this. 
1. Yes after logout user should be navigated to the login page.
2. Since there is no use for the key value pairs after logout, you can delete them.

**Comment by Penguin-12** [comment]
Closed via PR #34
