### ISSUE TITLE
Add a back button to the chat app bar.

### ISSUE THREAD

**Issue by Penguin-12** [PrarabdhGarg/Radar#26]
Since the appbar used in chat screen is a custom one, flutter doesn't generate a back button for it. Hence a back button would have to be added to it manually which should navigate the user to the requests screen.

**Comment by maplerichie** [comment]
Pull request sent. Forget to inform for assignment before this. Thanks

**Comment by akhil2000mittal** [comment]
i would like to help you with that

**Comment by Penguin-12** [comment]
> i would like to help you with that

@maplerichie has already submitted a PR for this, you can pick another issue for now.
