### ISSUE TITLE
Add a logout confirmation dialog

### ISSUE THREAD

**Issue by Penguin-12** [PrarabdhGarg/Radar#35]
Logout has been implemented, but it would be better to include a confirmation dialog in between to prevent accidental clicks.

**Comment by maplerichie** [comment]
Pull request sent. Forget to inform for assignment before this. Thanks

**Comment by akhil2000mittal** [comment]
I would be happy to help you with that

**Comment by Penguin-12** [comment]
> I would be happy to help you with that

@maplerichie has already submitted a PR for this, you can pick another issue for now.
