### ISSUE TITLE
Storing data in Flutter Secure Storage should happen in the AuthRepository instead of the LoginScreen

### ISSUE THREAD

**Issue by PrarabdhGarg** [PrarabdhGarg/Radar#7]
Since we need a clear separation between the view, and the model, the task of reading and writing data to the Flutter Secure Storage should be a part of the Repository and not the view. The view must be completely independent of the source it receives data from.

**Comment by pavankalyan0424** [comment]
I would like to work on this issue.

**Comment by PrarabdhGarg** [comment]
Great. Go ahead

**Comment by PrarabdhGarg** [comment]
Closed via #16
