### ISSUE TITLE
Store username and avatar in Secure Storage at login

### ISSUE THREAD

**Issue by PrarabdhGarg** [PrarabdhGarg/Radar#8]
Currently, while logging in, only the uid is getting stored in the Secure Storage. The display name of the user, as well as his/her avatar must be stored, for further use later.

**Comment by akshatgarg18** [comment]
I would like to work on this

**Comment by Garg-Akshat** [comment]
in the authrepository it is already been stored, so i think this issue must be closed

**Comment by Penguin-12** [comment]
> in the authrepository it is already been stored, so i think this issue must be closed

Yes, thanks for pointing out.
