### ISSUE TITLE
Update Login Screen UI

### ISSUE THREAD

**Issue by PrarabdhGarg** [PrarabdhGarg/Radar#9]
The link for the updated UI of the login page is: 
https://xd.adobe.com/view/3884d012-2dd1-4f15-bfa3-e80f6e45e473-6dd7/screen/5d7b2b92-ee86-4d67-a235-ae1b3ba0fa57/
You might need to modify the file `lib/auth/view/LoginScreen.dart`
The illustration can be found at:
https://drive.google.com/file/d/1rJM_JtEA4erAbe0W4dvb0NSKSwiebuSL/view?usp=sharing

**Comment by rish07** [comment]
Hey @PrarabdhGarg, I would like to work on this issue.

**Comment by PrarabdhGarg** [comment]
Sure. Go ahead.

**Comment by PrarabdhGarg** [comment]
@rish07 I am unassigning you this because of inactiveness.

**Comment by error404-beep** [comment]
Hey @PrarabdhGarg , I would like to work on this issue.

**Comment by PrarabdhGarg** [comment]
Sure. Go ahead.

**Comment by error404-beep** [comment]
Hey, Just wanted to confirm, should I follow a dynamic sizing approach like MediaQuery or simply follow the constraints given in the XD design.

**Comment by PrarabdhGarg** [comment]
If you can build a responsive layout, nothing like it

**Comment by PrarabdhGarg** [comment]
Closed via #19
